import { ReactElement } from "react";
import Head from "next/head";
import { Header } from "@components/Header";

export default function Layout({ children }: { children: ReactElement }) {
  return (
    <>
      <Head>
        <title>Create Next App !!!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span>Some Footer</span>
        </a>
      </footer>
    </>
  );
}
